name: Build and upload React app to EC2 instance
on:
  push:
    branches:
      - main
jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs
          sudo apt-get install -y npm
      - name: Build React app
        # run: |
        #   cd front
        #   npm install
        #   npm run build
      - name: Upload build folder to EC2 instance
        env:
          SSH_PEM_FILE: ${{ secrets.FRONT_PEM }}
          EC2_USER: ${{ secrets.FRONT_USER }}
          EC2_HOST: ${{ secrets.FRONT_HOST }}
        run: |
          echo "${SSH_PEM_FILE}" > frontend.pem
          chmod 600 frontend.pem
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa ${EC2_HOST} >> ~/.ssh/known_hosts
          scp -i /home/runner/work/actions_practice/actions_practice/frontend.pem -r ./build ${EC2_USER}@${EC2_HOST}:/home/ubuntu/www
