name: Front
on:
  push:
    branches:
      - main
    paths:
      - "front/**"
jobs:
  build_and_upload:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build React app
        run: |
          cd front
          npm install
          npm run build
      - name: Upload build folder to EC2 instance
        env:
          SSH_PEM_FILE: ${{ secrets.FRONT_PEM }}
          EC2_USER: ${{ secrets.FRONT_USER }}
          EC2_HOST: ${{ secrets.FRONT_HOST }}
        run: |
          echo "${SSH_PEM_FILE}" > frontend.pem
          echo $(ls)
          chmod 600 frontend.pem
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa ${EC2_HOST} >> ~/.ssh/known_hosts
          scp -i frontend.pem -r ./front/build ${EC2_USER}@${EC2_HOST}:/home/ubuntu/www
